{.passL: "`pkg-config rpm --libs`".}
{.passC: "`pkg-config rpm --cflags`".}

import futhark
importc:
  path "/usr/include/rpm/"
  "argv.h"
  "header.h"
  "rpmarchive.h"
  "rpmbase64.h"
  "rpmbuild.h"
  "rpmcallback.h"
  "rpmcli.h"
  "rpmcrypto.h"
  "rpmdb.h"
  "rpmds.h"
  "rpmfc.h"
  "rpmfi.h"
  "rpmfiles.h"
  "rpmfileutil.h"
  "rpmio.h"
  "rpmkeyring.h"
  "rpmlib.h"
  "rpmlog.h"
  "rpmmacro.h"
  "rpmpgp.h"
  "rpmplugin.h"
  "rpmprob.h"
  "rpmps.h"
  "rpmsign.h"
  "rpmspec.h"
  "rpmsq.h"
  "rpmstring.h"
  "rpmstrpool.h"
  "rpmsw.h"
  "rpmtag.h"
  "rpmtd.h"
  "rpmte.h"
  "rpmts.h"
  "rpmtypes.h"
  "rpmurl.h"
  "rpmutil.h"
  "rpmver.h"